import { Router } from 'express';
import { verifyJWT } from '../../middlewares/auth.middleware.js';
import { requireRole } from '../../middlewares/rbac.middleware.js';
import { auditMiddleware } from '../../middlewares/audit.middleware.js';
import { ADMIN_ROLES } from '../../config/constants.js';
import cityRoutes from './city.routes.js';
import pincodeRoutes from './pincode.routes.js';
import userRoutes from './user.routes.js';
import staffRoutes from './staff.routes.js';
import categoryRoutes from './category.routes.js';
import productRoutes from './product.routes.js';
import sectionRoutes from './section.routes.js';
import homeBannerRoutes from './homeBanner.routes.js';
import galleryRoutes from './gallery.routes.js';
import mediaRoutes from './media.routes.js';
import addOnRoutes from './addon.routes.js';
import addOnCategoryRoutes from './addOnCategory.routes.js';
import variantPresetRoutes from './variantPreset.routes.js';
import bannerRoutes from './banner.routes.js';
import slotRoutes from './slot.routes.js';
import slotBlackoutRoutes from './slotBlackout.routes.js';
import orderRoutes from './order.routes.js';
import paymentRoutes from './payment.routes.js';
import couponRoutes from './coupon.routes.js';
import reviewRoutes from './review.routes.js';
import enquiryRoutes from './enquiry.routes.js';
import testimonialRoutes from './testimonial.routes.js';
import pageRoutes from './page.routes.js';
import faqRoutes from './faq.routes.js';
import blogRoutes from './blog.routes.js';
import settingRoutes from './setting.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import auditLogRoutes from './auditLog.routes.js';
import notificationRoutes from './notification.routes.js';
import exportRoutes from './export.routes.js';
import shopCategoryRoutes from './shopCategory.routes.js';
import shopProductRoutes from './shopProduct.routes.js';
import shopOrderRoutes from './shopOrder.routes.js';
import shopReviewRoutes from './shopReview.routes.js';
import shiprocketRoutes from './shiprocket.routes.js';

const router = Router();

// Applied once here rather than per-route — every module mounted below inherits it.
router.use(verifyJWT, requireRole(...ADMIN_ROLES), auditMiddleware);

router.use('/cities', cityRoutes);
router.use('/pincodes', pincodeRoutes);
router.use('/users', userRoutes);
router.use('/staff', staffRoutes);
router.use('/categories', categoryRoutes);
router.use('/products', productRoutes);
router.use('/sections', sectionRoutes);
router.use('/home-banners', homeBannerRoutes);
router.use('/gallery', galleryRoutes);
router.use('/media', mediaRoutes);
router.use('/addons', addOnRoutes);
router.use('/addon-categories', addOnCategoryRoutes);
router.use('/variant-presets', variantPresetRoutes);
router.use('/banners', bannerRoutes);
router.use('/slots', slotRoutes);
router.use('/slot-blackouts', slotBlackoutRoutes);
router.use('/orders', orderRoutes);
router.use('/payments', paymentRoutes);
router.use('/coupons', couponRoutes);
router.use('/reviews', reviewRoutes);
router.use('/enquiries', enquiryRoutes);
router.use('/testimonials', testimonialRoutes);
router.use('/pages', pageRoutes);
router.use('/faqs', faqRoutes);
router.use('/blogs', blogRoutes);
router.use('/settings', settingRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/audit-logs', auditLogRoutes);
router.use('/notifications', notificationRoutes);
router.use('/export', exportRoutes);
router.use('/shop-categories', shopCategoryRoutes);
router.use('/shop-products', shopProductRoutes);
router.use('/shop-orders', shopOrderRoutes);
router.use('/shop-reviews', shopReviewRoutes);
router.use('/shiprocket', shiprocketRoutes);

export default router;
