module.exports = {
  apps: [
    {
      name: "humsafar-server",
      cwd: "./server",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 4004,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      error_file: "/root/.pm2/logs/humsafar-server-error.log",
      out_file: "/root/.pm2/logs/humsafar-server-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
    {
      name: "humsafar-client",
      cwd: "./client",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 3004,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "800M",
      error_file: "/root/.pm2/logs/humsafar-client-error.log",
      out_file: "/root/.pm2/logs/humsafar-client-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
    {
      name: "humsafar-admin",
      cwd: "./admin",
      script: "npm",
      args: "run preview -- --port 4177 --host 0.0.0.0",
      env: {
        NODE_ENV: "production",
        PORT: 4177,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      error_file: "/root/.pm2/logs/humsafar-admin-error.log",
      out_file: "/root/.pm2/logs/humsafar-admin-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
  ],
};
